name: socket_mobile
description: Socket Mobile Capture SDK
version: 1.0.0
homepage: https://github.com/jonathantribouharet/flutter_socket_mobile

environment:
  sdk: ">=2.17.0 <3.0.0"
  

dependencies:
  equatable: any
  flutter:
    sdk: flutter
  json_annotation: 4.4.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  json_serializable: any
  build_runner:

flutter:
  plugin:
    platforms:
      android:
        package: co.eivo.socket_mobile
        pluginClass: SocketMobilePlugin
      ios:
        pluginClass: SocketMobilePlugin
